site_name: Custom Pod Autoscaler
theme: material
markdown_extensions:
  - mdx_truly_sane_lists
  - codehilite
plugins:
  - search
nav:
- Home: 'index.md'
- 'User Guide':
  - Installation: 'user-guide/installation.md'
  - 'Getting Started': 'user-guide/getting-started.md'
  - 'Metric Gathering': 'user-guide/metric-gathering.md'
  - Evaluating: 'user-guide/evaluating.md'
  - Methods: 'user-guide/methods.md'
  - Hooks: 'user-guide/hooks.md'
  - 'Run Types': 'user-guide/run-types.md'
  - Cooldown: 'user-guide/cooldown.md'
  - 'Rest API': 'user-guide/rest-api.md'
  - 'Zero Scaling': 'user-guide/scaling-to-and-from-zero.md'
  - 'Kubernetes Metrics': 'user-guide/kubernetes-metrics.md'
- Reference:
  - Configuration: 'reference/configuration.md'
  - 'Docker Images': 'reference/docker-images.md'
  - 'Scaling Targets': 'reference/scaling-targets.md'
  - 'Rest API':
    - v1: 'reference/rest-api/v1.md'
